#Test Workflow (test.yml): This workflow pulls the Docker image from the registry and runs it, succeeding only if the score returned is greater than 0.50. It runs only if the Train workflow succeeds.


name: Test

on:
  workflow_run:
    workflows: ["Train"]
    types:
      - completed
      - requested

jobs:
  pull-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Train workflow was successful
        id: check_train_status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
            echo "Train workflow did not succeed. Forcing Test workflow to fail."
            exit 1
          fi

      - name: Pull Docker image
        run: docker pull krpushpam/assignment_3:latest

      - name: Run Docker image and check score
        run: |
          SCORE=$(docker run --rm krpushpam/assignment_3:latest)
          echo "Score: $SCORE"
          if (( $(echo "$SCORE > 0.50" | bc -l) )); then
            echo "Success: Score is greater than 0.50"
          else
            echo "Failure: Score is not greater than 0.50"
            exit 1
